config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'contacts#search'

  get 'contacts/index'
  get 'contacts/new'
  get 'contacts/edit'
  get 'contacts/show'
  get 'contacts/delete'
  get 'contacts/search'
  get 'contacts/database'
  resources :contacts do
    collection do
      post :import
    end
  end

  resources :km do
    collection do
      get :roles
      get :birthdays
    end
  end
end

app/models/contact.rb
# frozen_string_literal: true
class Contact < ActiveRecord::Base
  # before_save :downcase_fields

  before_save :to_i
  has_attached_file :image,
                    styles: { large: '600x600#', medium: '300x300#', thumb: '150x150#' },
                    default_url: '/assets/:style/default_image.jpg'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :name, presence: true
  validates :gender, inclusion: { in: %w(male female), message: '%{value} is not a real gender.' }, allow_nil: true

  belongs_to :contact_group, primary_key: :contact_id, foreign_key: :id
  has_one :contact_birthday, primary_key: :id, foreign_key: :contact_id
  has_many :contact_roles, primary_key: :id, foreign_key: :contact_id

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |contact|
        csv << contact.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      contact = find_by_id(row['id']) || new
      contact.attributes = row.to_hash
      contact.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when '.csv'
      Roo::Csv.new(file.path, nil, :ignore)
    when '.xls'
      Roo::Excel.new(file.path, nil, :ignore)
    when '.xlsx'
      Roo::Excelx.new(file.path, nil, :ignore)
    else
      raise "Unknown file type: #{file.original_filename}"
    end
  end

  #   def downcase_fields
  #     self.name.try(:downcase!)
  #     self.email.try(:downcase!)
  #     self.address_building.try(:downcase!)
  #     self.address_city.try(:downcase!)
  #     self.other_1.try(:downcase!)
  #     self.other_2.try(:downcase!)
  #     self.other_3.try(:downcase!)
  #   end
  def to_i
    self.address_zip = address_zip.to_i
  end

  def self.search(term)
    contacts = Contact.all.order('created_at DESC')
    contacts.select do |contact|
      contact.attributes.any? { |_key, val| val.to_s.include?(term) }
    end
  end

  def male?
    gender == 'male'
  end

  def female?
    gender == 'female'
  end
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true
class ContactsController < ApplicationController
  ACCEPTED_EXTENSIONS = %w(.xlsx .xls .csv).freeze

  before_action :authenticate_user!
  before_action :check_admin!, except: [:search]
  before_action :check_accessibility!, except: [:index, :show, :search]

  def index
    initialize_all_contacts

    respond_to do |format|
      format.html
      format.csv { send_data @contacts.to_csv }
      format.xls
      format.xlsx
    end
  end

  def search
    initialize_all_contacts
  end

  def show
    initialize_contact
  rescue ActiveRecord::RecordNotFound
    redirect_to contacts_path, notice: 'This entry does not exist.'
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(user_params)
    @contact.save!
    redirect_to contacts_path, notice: 'Successfully Created.'
  rescue => e
    # Captures any exceptions and display error message on page
    flash[:notice] = e.message
    render 'new'
  end

  def edit
    initialize_contact
  end

  def update
    initialize_contact
    @contact.update_attributes!(user_params)
    # redirect_to contacts_path, :notice => 'Successfully updated.'
    redirect_to show, notice: 'Successfully updated.'

  rescue => e
    # Captures any exceptions and display error message on page
    flash[:notice] = e.message
    render 'edit'
  end

  def destroy
    initialize_contact
    @contact.destroy!
    redirect_to contacts_path, notice: 'Successfully deleted.'
  rescue => e
    # Captures any exceptions and display error message on page
    flash[:notice] = e.message
    render 'show'
  end

  def import
    if params[:file].nil?
      redirect_to contacts_database_path, notice: 'No file selected'
    elsif !ACCEPTED_EXTENSIONS.include?(File.extname(params[:file].original_filename))
      redirect_to contacts_database_path, notice: 'Incompatible file type'
    else
      Contact.import(params[:file])
      redirect_to contacts_path, notice: 'Contacts successfully imported!'
    end
  end

  # def download
  #  @contacts = Contact.all
  #  respond_to do |format|
  #     format.xlsx {render xlsx: 'download',filename: "contacts.xlsx"}
  #  end
  # end

  private

  def check_admin!
    redirect_to '/', notice: "You don't have permissions to access" unless current_user.r_admin? || current_user.rwx_admin?
  end

  def check_accessibility!
    redirect_to '/', notice: "You don't have permissions to access" unless current_user.rwx_admin?
  end

  def initialize_contact
    @contact = Contact.find(params[:id])
  end

  def initialize_all_contacts
    @contacts = if params[:search]
                  Contact.search(params[:search])
                else
                  Contact.all.order('created_at DESC')
    end
  end

  def user_params
    params.require(:contact).permit(
      :name,
      :birthday,
      :phone,
      :position,
      :sa_yeok,
      :mok_jang,
      :sun_kyo,
      :email,
      :address_building,
      :address_city,
      :address_zip,
      :address_state,
      :other_1,
      :other_2,
      :other_3,
      :image,
      :created_at,
      :updated_at
    )
  end
end

app/helpers/contacts_helper.rb
# frozen_string_literal: true
module ContactsHelper
  def google_link_converter(contact)
    google_address = 'http://maps.google.com/?q=%s,%s,%s,%s' % [
      contact.address_building,
      contact.address_city,
      contact.address_state,
      contact.address_zip
    ]

    link_to google_address, target: '_blank' do
      '%s, %s, %s %s' % [
        contact.address_building.split.map(&:capitalize).join(' '),
        contact.address_city.split.map(&:capitalize).join(' '),
        contact.address_state,
        contact.address_zip
      ]
    end
  end
end

app/views/contacts/database.html.erb
<header><h1 id="home"> Database Import/Export </h1></header>

<div id="main_frame">
  <p id="download">
    <i style="font-size:2.4em;" class="fa fa-download" aria-hidden="true">&nbsp;</i>
    Download Contacts Database:<br /><br />
    <%= link_to ".csv", contacts_path(format: "csv") %> |
    <%= link_to ".xls", contacts_path(format: "xls") %> |
    <%= link_to '.xlsx (Recommended)', contacts_path(format: :xlsx) %>
  </p>

  <p id="download">
    <i style="font-size:2.4em;" id="font-awesome" class="fa fa-upload" aria-hidden="true">&nbsp;</i>
     Import Contacts Database:&nbsp;&nbsp;
    <%= form_tag import_contacts_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag 'Import',{:class => "button scrolly",:id => "database_import", :confirm =>"Are you sure to import new contacts?"} %>
    <% end %>
  </p>
</div>

app/views/contacts/edit.html.erb
<header><h1 id="home">Edit contacts</h1></header>

<div id="create_new_form">
  <%= form_for  @contact do |f| %>
    <p>
      이름:
      <%= f.text_field :name %><br />
    </p>
    <p>
     생일:
     <%= f.date_select :birthday,:start_year=>Date.today.year - 100,:end_year=>Date.today.year %>
    </p>
    <p>
     전화번호:
     <%= f.text_field :phone %><br />
    </p>
    <p>
      직분 :
      <%= f.select :position, position, { include_blank: true } %>
    </p>
    <p>
      사역 :
      <%= f.select :sa_yeok, sa_yeok, { include_blank: true } %>
    </p>
    <p>
      목장 :
      <%= f.select :mok_jang, mok_jang, { include_blank: true } %>
    </p>
    <p>
      선교회:
      <%= f.select :sun_kyo, sun_kyo, { include_blank: true } %>
    </p>
    <p>
      이메일:
      <%= f.text_field :email %><br />
    </p>
    <p>
      Address:
      <%= f.text_field :address_building %><br />
    </p>
    <p>
      City:
      <%= f.text_field :address_city %><br />
    </p>
    <p>
      State:
      <%= f.select :address_state, states, { include_blank: true }%>
    </p>
    <p>
      Zipcode:
      <%= f.text_field :address_zip %><br />
    </p>
    <p>
      비고 1:
      <%= f.text_field :other_1 %><br />
    </p>
    <p>
      비고 2:
      <%= f.text_field :other_2 %><br />
    </p>
    <p>
      비고 3:
      <%= f.text_field :other_3 %><br />
    </p>
    <p>
      사진:<br /><br />
      <%= f.file_field :image %><br />
    </p>
    <p id="button">
      <%= f.submit 'Update' ,{:class => "button scrolly",:id => "show_button create_new_form"} %>
      <%= link_to 'Cancel', contacts_path, {:class => "button scrolly",:id => "show_button create_new_form"} %>
    </p>
  <% end %>
</div>

app/views/contacts/index.html.erb
<header><h1 id="home">Welcome to Contacts!!</h1></header>

<div id="main_frame">
  <div id="search-home">
    <%= form_tag(contacts_path, :method => "get", id: "search-input-home") do %>
      <%= text_field_tag :search,params[:search], placeholder: "키워드를 입력하세요..." %>
      <%= submit_tag "검색", :id => "submit" %>
    <% end %>

    <div id="message">
      <% unless @contacts.present? %>
        <p>There are no contacts containing the term(s): <%= params[:search] %>.</p>
      <% end %>


    </div>
  </div>

  <table id="home">
    <tr id="header-table-index">
      <th id="name" width="100px">이름</th>
      <th id="birthday" width="120px">생일</th>
      <th id="phone" width="135px">전화번호</th>
      <th id="position" width="80px">직분</th>
      <th id="sa_yeok" width="100px">사역</th>
      <th id="mok_jang" width="120px">목장</th>
      <th id="sun_kyo" width="120px">선교</th>
      <th id="email" width="120px">이메일</th>
      <th id="address" width="">주소</th>
    </tr>

    <% @contacts.each do |f| %>
      <tr>
        <td id="name"><%= link_to f.name.to_s.split.map(&:capitalize).join(' '), f %></td>
        <td id="birthday">
          <% if f.birthday %>
            <%= f.birthday && f.birthday.strftime('%Y-%m-%d') %>
          <% else %>
            &nbsp;
          <% end %>
        </td>
        <td id="phone">
          <% unless f.phone.nil? %>
            <%= link_to number_to_phone(f.phone, area_code:true), "tel:#{f.phone}" %></td>
          <% else %>
            &nbsp;
          <% end %>
        </td>
        <td id="position"><%= f.position %></td>
        <td id="sa_yeok"><%= f.sa_yeok %></td>
        <td id="mok_jang"><%= f.mok_jang %></td>
        <td id="sun_kyo"><%= f.sun_kyo %></td>
        <td id="email"><%= mail_to f.email %></td>
        <td id="address">
          <% if f.address_building %>
            <%= google_link_converter(f) %>
          <% else %>
            &nbsp;
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/contacts/index.xls.erb
<table border="1">
  <tr>
    <th>ID</th>
    <th>이름</th>
    <th>나이</th>
    <th>생일</th>
    <th>전화번호</th>
    <th>직분</th>
    <th>사역</th>
    <th>목장</th>
    <th>선교회</th>
    <th>이메일</th>
    <th>주소</th>
    <th>도시</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>도시</th>
    <th>비고 1</th>
    <th>비고 2</th>
    <th>비고 3</th>
    <th>created_at</th>
    <th>updated_at</th>
    <th>image_file_name</th>
    <th>image_content_type</th>
    <th>image_file_size</th>
    <th>image_updated_at</th>
  </tr>
  <%= @contacts.each do |f| %>
    <tr>
      <td><%= f.id %></td>
      <td><%= f.name %></td>
      <td><%=Time.now.year - f.birthday.strftime("%Y").to_i %></td>
      <td><%=f.birthday.strftime("%Y")%>-<%=f.birthday.strftime("%m")%>-<%=f.birthday.strftime("%d")%></td>
      <td><%= number_to_phone(f.phone.to_i, area_code:true)%></td>
      <td><%=f.position%></td>
      <td><%=f.sa_yeok%></td>
      <td><%=f.mok_jang%></td>
      <td><%=f.sun_kyo%></td>
      <td><%=f.email%></td>
      <td><%=f.address_building%></td>
      <td><%=f.address_city%></td>
      <td><%=f.address_state%></td>
      <td><%=f.address_zip%></td>
      <td><%=f.other_1%></td>
      <td><%=f.other_2%></td>
      <td><%=f.other_3%></td>
      <td><%=f.created_at%></td>
      <td><%=f.updated_at%></td>
      <td><%=f.image_file_name%></td>
      <td><%=f.image_content_type%></td>
      <td><%=f.image_file_size%></td>
      <td><%=f.image_updated_at%></th>
    </tr>
  <% end %>
</table>

app/views/contacts/new.html.erb
<header><h1 id="home">Create new contacts</h1></header>

<div id="create_new_form">
  <%= form_for  @contact, html: {multipart: true} do |f| %>
  <p>
    이름:
    <%= f.text_field :name %><br />
  </p>
  <p>
    생일:
    <%= f.date_select :birthday,:start_year=>Date.today.year - 100,:end_year=>Date.today.year %>
  </p>
  <p>
    전화번호:
    <%= f.text_field :phone %><br />
  </p>
  <p>
    직분 :
    <%= f.select :position, position, { include_blank: true } %>
  </p>
  <p>
    사역 :
    <%= f.select :sa_yeok, sa_yeok, { include_blank: true } %>
  </p>
  <p>
    목장 :
    <%= f.select :mok_jang, mok_jang, { include_blank: true } %>
  </p>
  <p>
    선교회:
    <%= f.select :sun_kyo, sun_kyo, { include_blank: true } %>
  </p>
  <p>
    이메일:
    <%= f.text_field :email %><br />
  </p>
  <p>
    Address:
    <%= f.text_field :address_building %><br />
  </p>
  <p>
    City:
    <%= f.text_field :address_city %><br />
  </p>
  <p>
    State:
    <%= f.select :address_state, states, { include_blank: true }%>
  </p>
  <p>
    Zipcode:
    <%= f.text_field :address_zip %><br />
  </p>
  <p>
    비고 1:
    <%= f.text_field :other_1 %><br />
  </p>
  <p>
    비고 2:
    <%= f.text_field :other_2 %><br />
  </p>
  <p>
    비고 3:
    <%= f.text_field :other_3 %><br />
  </p>
  <p>
    사진:<br /><br />
    <%= f.file_field :image%><br />
  </p>
  <p id="button">
    <%= f.submit 'Create' ,{:class => "button scrolly",:id => "show_button create_new_form"} %>
      <%= link_to 'Cancel', contacts_path, {:class => "button scrolly",:id => "show_button create_new_form"} %>
    <% end %>
  </p>
</div>

app/views/contacts/search.html.erb
<header id="search-heading"><h1>Search?</h1></header>

<div id="search">
  <%= form_tag(contacts_path, :method => "get", id: "search-input") do %>
    <%= text_field_tag :search,params[:search], placeholder: "키워드를 입력하세요..." %>
    <%= submit_tag "검색", :id => "submit" %>
  <% end %>
</div>

app/views/contacts/show.html.erb
<div id="show-body">
  <div id="show">
    <div id="show-image">
      <span id="image"><%=image_tag @contact.image.url(:medium)%></span>
    </div>
    <div id="show-content">
      <header id="show-header" >
        <h1>Hi. My name is <strong><%= @contact.name.split.map(&:capitalize).join(' ') %></strong>.</h1>
      </header>
      <table id="show-table">
        <tr>
          <td id="show_key">이름: </td>
          <td id="show_value"><%= @contact.name.split.map(&:capitalize).join(' ') %></td>
        </tr>
        <tr>
          <td id="show_key">생년월일: </td>
          <td id="show_value"><%= @contact.birthday.try(:strftime, '%Y년 %m월 %d일') %></td>
        </tr>
        <tr>
          <td id="show_key">전화번호: </td>
          <td id="show_value">
            <% unless @contact.phone.nil? %>
              <%= link_to number_to_phone(@contact.phone, area_code:true), "tel:#{@contact.phone.to_i}"%>
            <% end %>
          </td>
        </tr>
        <tr>
          <td id="show_key">이메일: </td>
          <td id="show_value"><%= mail_to "#{@contact.email}" %></td>
        </tr>
        <tr>
          <td id="show_key">주소: </td>
          <td id="show_value" style="height:60px;">
            <% if @contact.address_building %>
              <%= link_to("http://maps.google.com/?q=#{@contact.address_building},#{@contact.address_city}, #{@contact.address_state} #{@contact.address_zip}",:target => "_blank") do %>
                <%= @contact.address_building.split.map(&:capitalize).join(' ') %>
                <br />
                <%= @contact.address_city.split.map(&:capitalize).join(' ') %>, <%= @contact.address_state %> <%= @contact.address_zip %>
              <% end %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td id="show_key">직분: </td>
          <td id="show_value"><%= @contact.position %></td>
        </tr>
        <tr>
          <td id="show_key">사역: </td>
          <td id="show_value"><%= @contact.sa_yeok %></td>
        </tr>
        <tr>
          <td id="show_key">목장: </td>
          <td id="show_value"><%= @contact.mok_jang %></td>
        </tr>
        <tr>
          <td id="show_key">선교: </td>
          <td id="show_value"><%= @contact.sun_kyo %></td>
        </tr>
        <tr>
          <td id="show_key">비고 1: </td>
          <td id="show_value"><%= @contact.other_1 %></td>
        </tr>
        <tr>
          <td id="show_key">비고 2: </td>
          <td id="show_value"><%= @contact.other_2 %></td>
        </tr>
        <tr>
          <td id="show_key">비고 3: </td>
          <td id="show_value"><%= @contact.other_3 %></td>
        </tr>
      </table>
    </div>
  </div>
  <div id="show-button">
    <div id="show-back">
      <%= link_to 'Back', contacts_path, {:class => "button big scrolly",:id => "show_button"} %>
    </div>
    <% if current_user.rwx_admin? %>
    <div id="show-edit">
      <%= link_to 'Edit', edit_contact_path, {:class => "button big scrolly",:id => "show_button"} %>
    </div>
    <div id="show-delete">
      <%= link_to 'Delete', @contact, {:class=>"button big scrolly",:id=>"show_button",:method => :delete, data:{:confirm =>"Are you sure?"} }%>
    </div>
    <% end %>
  </div>
</div>